\documentclass[10pt]{article}
\usepackage{hyperref}
\usepackage{url}
\usepackage[a4paper]{geometry}
\usepackage{a4wide}
\usepackage{float}
\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage{csquotes}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{xspace}
\usepackage[numbers]{natbib}
\bibliographystyle{unsrtnat}
\usepackage{subcaption}
\usepackage[font={small}]{caption}
\usepackage{booktabs}
\usepackage{listings}
\usepackage{cleveref}
\usepackage{lipsum}
\newcommand{\approxtext}[1]{\ensuremath{\stackrel{\text{#1}}{=}}}
\newcommand{\matr}[1]{\mathbf{#1}}
\newcommand{\partt}[2]{\ensuremath{\dfrac{\partial {#1}}{\partial {#2}}}}
\renewcommand{\d}[1]{\ensuremath{\operatorname{d}\!{#1}}} % non-italized differentials
\newcommand{\h}[0]{\ensuremath{\hbar}} % hbar
\def\changemargin#1#2{\list{}{\rightmargin#2\leftmargin#1}\item[]}
\let\endchangemargin=\endlist 
\usepackage{amsthm}
\theoremstyle{plain}
\renewcommand{\theequation}{\thesection.\arabic{equation}}
\def\changemargin#1#2{\list{}{\rightmargin#2\leftmargin#1}\item[]}
\let\endchangemargin=\endlist    
\usepackage{xcolor}
\definecolor{Red}{rgb}{0.7,0,0}
\definecolor{Blue}{rgb}{0,0,0.8}
\usepackage{verbatim}
\def\changemargin#1#2{\list{}{\rightmargin#2\leftmargin#1}\item[]}
\let\endchangemargin=\endlist
\addtolength{\oddsidemargin}{-.35in}
\addtolength{\evensidemargin}{-.35in}
\addtolength{\textwidth}{.7in}
\usepackage{multicol}

% Stephen's stuff
\newcommand{\R}{\texttt{R}}
\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\mbox{\normalfont\textsf{#1}}}}
\usepackage{xcolor}
\definecolor{Red}{rgb}{0.7,0,0}
\definecolor{Blue}{rgb}{0,0,0.8}
\hypersetup{%
pdfusetitle,
bookmarks = {true},
bookmarksnumbered = {true},
bookmarksopen = {true},
bookmarksopenlevel = 2,
unicode = {true},
breaklinks = {false},
hyperindex = {true},
colorlinks = {true},
linktocpage = {true},
plainpages = {false},
linkcolor = {Blue},
citecolor = {Blue},
urlcolor = {Red},
pdfstartview = {Fit},
pdfpagemode = {UseOutlines},
pdfview = {XYZ null null null}
}
%% Listings
\lstset{ 
language=R,                     % the language of the code
basicstyle=\footnotesize,       % the size of the fonts that are used for the code
numbers=left,                   % where to put the line-numbers
numberstyle=\tiny\color{gray},  % the style that is used for the line-numbers
stepnumber=1,                   % the step between two line-numbers. If it's 1, each line will be numbered
numbersep=5pt,                  % how far the line-numbers are from the code
backgroundcolor=\color{white},  % choose the background color. You must add \usepackage{color}
showspaces=false,               % show spaces adding particular underscores
showstringspaces=false,         % underline spaces within strings
showtabs=false,                 % show tabs within strings adding particular underscores
rulecolor=\color{black},        % if not set, the frame-color may be changed on line-breaks within not-black text (e.g. commens (green here))
tabsize=2,                      % sets default tabsize to 2 spaces
captionpos=b,                   % sets the caption-position to bottom
breaklines=true,                % sets automatic line breaking
breakatwhitespace=false,        % sets if automatic breaks should only happen at whitespace
title=\lstname,                 % show the filename of files included with \lstinputlisting;
% also try caption instead of title
keywordstyle=\color{Blue},      % keyword style
commentstyle=\color{orange},    % comment style
stringstyle=\color{Red},        % string literal style
escapeinside={\%*}{*)},         % if you want to add a comment within your code
morekeywords={*,...}            % if you want to add more keywords to the set
} 


%%% Document specific
\newcommand{\course}{Population Genetics}
\newcommand{\ass}{2}
\newcommand{\term}{Lent term 2017}
%\bibliography{pga1}

%%% Title page
\title{
  \bf \course: Assignment \ass \\[1em]
  \small{University of Cambridge}
}

\author{Henrik Åhl}
\date{\today}
\renewcommand{\textfraction}{0.05}
\renewcommand{\topfraction}{0.8}
\renewcommand{\bottomfraction}{0.8}
\renewcommand{\floatpagefraction}{0.75}

%%% Actual document
\begin{document}
\date{\today}
\maketitle
\setcounter{page}{1}

<<setup, include=FALSE, cache=FALSE, echo = FALSE, warning=FALSE, message = FALSE>>=
library(knitr)
opts_chunk$set(fig.path='figure/twocolumn-', fig.align='center', fig.show='hold')
render_listings()
@
% \date{\today}
\maketitle
\begin{abstract}
{\bf 
  %\begin{changemargin}{-.8cm}{-.8cm}
  This is an abstract abstract.
}
\end{abstract}

\begin{multicols*}{2}
\section*{Preface}
This is an assignment report in connection to the \textit{\course}
module in the Computational Biology course at the University of Cambridge,
\term. All related code is as of \date{\today} available through a
Github repository by contacting \href{mailto:hpa22@cam.ac.uk}{hpa22@cam.ac.uk}.
<<codeblock,include = F, echo = F, warning = F>>=
@
\section*{Exercises}
\subsection*{1}
<<inference, echo=FALSE, fig.height = 4.5, fig.env='figure', fig.cap="Things", cache = FALSE, fig.pos="H",fig.align='center'>>=
setwd("~/compbio/src/assignments/pga2/code/")
library(RColorBrewer)
palette(brewer.pal(n = 8, name = "Set1"))
library(scales)
library(stats4)
library(viridis)

# Parameters / data
N = 100
timepoints = 0:6
data = data.frame(time = 0:6, n = c(28, 39, 72, 83, 98, 96, 99) / N)
x = data[, "time"]
xs = seq(0, 6, 0.1)

# Fraction development over time
q = function(q.init, sigma, t) {
  q.init * exp(sigma * t) / (1 - q.init + q.init * exp(sigma * t))
}

# Calculate the log-likelihood
nas = data[,"n"]*N
prefact = factorial(N)/(sapply(nas, factorial)*sapply(N-nas, factorial))
log.lik = function(q.init, sigma){
  qas = q(q.init, sigma, timepoints)
  # nas = qas*N
  ln.p = log(prefact*qas**(nas)*((1-qas)**(N-nas))) 
  -sum(ln.p)   
}

fit = mle(minuslogl = log.lik, start = list(q.init = .5, sigma = .5), method="L-BFGS-B", lower = 0, upper=c(1, Inf)) 
coef = coef(summary(fit))

# Calculate upper and lower bound of estimate
yhigh = q(coef[1, 1] + coef[1, 2], coef[2, 1] + coef[2, 2], xs)
ylow = q(coef[1, 1] - coef[1, 2], coef[2, 1] - coef[2, 2], xs)

# Plot it all
plot(1, type="n", axes=T, xlab="Time [days]", ylab="Allele frequency", ylim=c(0,100/N), xlim = c(0,6), bty = "n")
polygon(c(xs, rev(xs)), c(yhigh, rev(ylow)),
          col = alpha(2, .33), border = F, lty = 2, lwd = 2)
lines(x, data[,"n"], type = "b", pch = 17, cex = 1.5, lwd = 3, col = 1)
lines(xs, q(coef[1, 1], coef[2, 1], xs), col = 2, lwd = 3, lty = 2)

# Plot borders
lines(xs, ylow, col = alpha(2, 1), lwd = 1)
lines(xs, yhigh, col = alpha(2, 1), lwd = 1)
@

<<inference2, echo=FALSE, fig.height = 4.5, fig.env='figure', fig.cap="Things", cache = TRUE, fig.pos="H",fig.align='center'>>=
qvals = seq(0, 1, 0.01)
svals = seq(0, 7.5, 0.02)

likelihoods = sapply(qvals, function(x)
  sapply(svals, function(y)
    log.lik(x, y)))

filled.contour((likelihoods),   xlab = expression(q[0]),  ylab = expression(sigma),
               col = viridis(22),
               axes = F
)
axis(1, at = seq(0, .75, 0.15), labels = round(seq(.1, 1, 1/.75 * .25/2), 2))
axis(2, at = seq(0, 1, 0.2), labels = seq(0, 7.5, 7.5 * 0.2))
axis(4, at = seq(0, .9, 0.15), labels = seq(0, 3000, 500), las =2, line= -2)
@

\bibliography{references}
\end{multicols*}
\end{document}
